# -*- coding: utf-8 -*-
"""model_classes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1sOMi1z0Hu5qC0vt2T-B8We96kN3JK-
"""

import pandas as pd
import numpy as np


from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from xgboost import XGBRegressor
import lightgbm as lgb

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import HistGradientBoostingRegressor


from sklearn.metrics import r2_score

from sklearn.metrics import mean_absolute_percentage_error
from sktime.performance_metrics.forecasting import median_absolute_percentage_error

# Preset Values

end_yr = 2026
end_mnth = 6


main_cols = ["BedroomsTotal", "BathroomsTotalInteger", "LivingArea", "LotSizeSquareFeet",
             "DaysOnMarket", "YearBuilt", "PostalCode", "SaleMonth"]

extras = ["ViewYN", "FireplaceYN", "NewConstructionYN", "PoolPrivateYN"]
extra_cols = [a+"_True" for a in extras] + [a+"_False" for a in extras]

totals = main_cols+extra_cols

crit_cols = totals + ['LivingArea/LotSizeSquareFeet', 'LotSizeSquareFeet/DaysOnMarket', 'LivingArea/DaysOnMarket',
                      'BathroomsTotalInteger/BedroomsTotal', 'AvgAreaCost', 'AvgAreaLot', 'AvgLivingArea', 'DistrictID']
log_cols = main_cols + ['LivingArea/LotSizeSquareFeet', 'LotSizeSquareFeet/DaysOnMarket', 'LivingArea/DaysOnMarket',
                        'BathroomsTotalInteger/BedroomsTotal', 'AvgAreaCost', 'AvgAreaLot', 'AvgLivingArea', 'DistrictID']


target = "ClosePrice"



class W4_Regression():

  def __init__(self,df):
    self.df = df


  def test_train_split(self, yr=end_yr, mo=end_mnth):
    """
    Takes a DataFrame
    Encodes "PropertyType" column
    Returns a defined training and test set for the DataFrame
    """
    yr_mo = []
    for i in self.df['CloseDate']:                                         # For each date in the "CloseDate" column
      yr, mo = i.year, i.month                                          # Define the year and month values of date i
      yr_mo.append([yr,mo])                                             # Append to "yr_mo" a list of date i's year and month
    te_set = [b for b in range(len(yr_mo)) if yr_mo[b] == [yr,mo]]   # Define a list of row #s with date 06/2026
    te_rng = te_set[0::len(te_set)-1]                                 # Define a list of the first and last row in "te_set"
    tr, te = self.df[0:te_rng[0]], self.df[te_rng[0]:te_rng[1]]             # Define the training and test sets of the inputted df
    return tr, te


  def LinReg(self, tr, te, feat=totals, targ=target):
    """
    Takes a training DataFrame, test DataFrame, and feature and target values
    Returns R2 score of the Linear Regression
    """
    x_tr = tr[feat].values            # Define the x_train set values
    y_tr = tr[targ].values            # Define the y_train set values
    x_te = te[feat].values            # Define the x_test set values
    y_te = te[targ].values            # Define the y_test set values

    model = LinearRegression()        # Define Linear Regression model
    model.fit(x_tr, y_tr)             # Fit training data to model
    y_pred = model.predict(x_te)      # Models the predicted y values from x_test values

    return y_te, y_pred


  def log_transform(self, feat=main_cols, targ=target):
    log_df = self.df.copy()
    for col in feat+[targ]:
      new_col = []
      for val in log_df[col]:
        new_col.append(float(np.log(val)))
      log_df[col] = pd.DataFrame(new_col)
    return log_df


  def r2_eval(self, y_test, y_pred):
    r2 = r2_score(y_test, y_pred)       # Computes the r2 score of y_test and the predicted y
    return r2

class W5_Regs():

  def __init__(self,df):
    self.df = df

    self.cols = self.df.columns.to_list()
    self.new_col_strt = [i for i in range(len(self.cols)) if self.cols[i] == "SaleMonth"]
    self.new_cols = self.cols[(self.new_col_strt[0]+1):len(self.cols)]
    self.new_cols = [i for i in self.new_cols if i != "DistrictName"]

    self.crit_cols = totals+self.new_cols
    self.log_cols = main_cols+self.new_cols


  def test_train_split(self, yr=end_yr, mo=end_mnth):
    """
    Takes a DataFrame
    Encodes "PropertyType" column
    Returns a defined training and test set for the DataFrame
    """
    yr_mo = []
    for i in self.df['CloseDate']:                                         # For each date in the "CloseDate" column
      yr, mo = i.year, i.month                                          # Define the year and month values of date i
      yr_mo.append([yr,mo])                                             # Append to "yr_mo" a list of date i's year and month
    te_set = [b for b in range(len(yr_mo)) if yr_mo[b] == [yr,mo]]   # Define a list of row #s with date 06/2026
    te_rng = te_set[0::len(te_set)-1]                                 # Define a list of the first and last row in "te_set"
    tr, te = self.df[0:te_rng[0]], self.df[te_rng[0]:te_rng[1]]             # Define the training and test sets of the inputted df
    return tr, te


  def TreeReg(self, tr, te, feat=totals, targ=target):
    """
    Takes a training DataFrame and test DataFrame
    """
    x_tr = tr[feat].values            # Define the x_train set values
    y_tr = tr[targ].values            # Define the y_train set values
    x_te = te[feat].values            # Define the x_test set values
    y_te = te[targ].values            # Define the y_test set values

    model = DecisionTreeRegressor(random_state=0)        # Define Decision Tree Regression model
    model.fit(x_tr, y_tr)             # Fit training data to model
    y_pred = model.predict(x_te)      # Models the predicted y values from x_test values
    return y_te, y_pred


  def ForestReg(self, tr, te, feat=totals, targ=target):
    """
    Takes a training DataFrame and test DataFrame
    """
    x_tr = tr[feat].values            # Define the x_train set values
    y_tr = tr[targ].values            # Define the y_train set values
    x_te = te[feat].values            # Define the x_test set values
    y_te = te[targ].values            # Define the y_test set values

    model = RandomForestRegressor(random_state=0)        # Define Random Forest Regression model
    model.fit(x_tr, y_tr)             # Fit training data to model
    y_pred = model.predict(x_te)      # Models the predicted y values from x_test values
    return y_te, y_pred


  def r2_eval(self, y_test, y_pred):
    r2 = r2_score(y_test, y_pred)       # Computes the r2 score of y_test and the predicted y
    return r2


  def shrt_main(self, model, trn, tes, evals, feats, rev=True, prt=True, **kwargs):

    scores = []
    for col in feats:
      try:
        y_te, y_pr = model(trn, tes, [col], dep=kwargs["dep"], l_rate=kwargs["l_rate"], est=kwargs["est"])
      except:
        try:
          y_te, y_pr = model(trn, tes, [col], dep=kwargs["dep"], l_rate=kwargs["l_rate"])
        except:
          y_te, y_pr = model(trn, tes, [col])
      scr = evals(y_te, y_pr)
      scores.append(scr)
    scr_lst = [[feats[i], scores[i]] for i in range(len(scores))]
    scr_lst = sorted(scr_lst, key=lambda x: x[1], reverse=rev)

    totals = []
    for i in range(1, len(scores)):
      maximum = i
      cols = [scr_lst[a][0] for a in range(maximum)]
      try:
        y_te, y_pr = model(trn, tes, cols, dep=kwargs["dep"], l_rate=kwargs["l_rate"], est=kwargs["est"])
      except:
        try:
          y_te, y_pr = model(trn, tes, cols, dep=kwargs["dep"], l_rate=kwargs["l_rate"])
        except:
          y_te, y_pr = model(trn, tes, cols)
      scr = evals(y_te, y_pr)
      totals.append([cols, scr])
    totals = sorted(totals, key=lambda x: x[1], reverse=rev)
    if prt == True:
      print(f"Correlation of {totals[0][0]}:\n {round(totals[0][1],4)}")

    return totals[0][0], totals[0][1]


  def lng_main(self, model, trn, tes, evals, feats, rev=True, prt=True, **kwargs):

    scores = []
    for col in feats:
      try:
        y_te, y_pr = model(trn, tes, [col], dep=kwargs["dep"], l_rate=kwargs["l_rate"], est=kwargs["est"])
      except:
        try:
          y_te, y_pr = model(trn, tes, [col], dep=kwargs["dep"], l_rate=kwargs["l_rate"])
        except:
          y_te, y_pr = model(trn, tes, [col])
      scr = evals(y_te, y_pr)
      scores.append(scr)
    scr_lst = [[feats[i], scores[i]] for i in range(len(scores))]
    scr_lst = sorted(scr_lst, key=lambda x: x[1], reverse=rev)

    totals = []
    for i in range(1, len(scores)):
      maximum = i
      cols = [scr_lst[a][0] for a in range(maximum)]
      try:
        y_te, y_pr = model(trn, tes, cols, dep=kwargs["dep"], l_rate=kwargs["l_rate"], est=kwargs["est"])
      except:
        try:
          y_te, y_pr = model(trn, tes, cols, dep=kwargs["dep"], l_rate=kwargs["l_rate"])
        except:
          y_te, y_pr = model(trn, tes, cols)
      scr = evals(y_te, y_pr)
      if prt == True:
        print(f"Correlation of {cols}: \t\t {round(scr,4)}")

      totals.append([cols, scr])
    totals = sorted(totals, key=lambda x: x[1], reverse=True)
    return totals[0][0], totals[0][1]

class W7_Boosting():

  def __init__(self,df):
    self.df = df


  def test_train_split(self, yr=end_yr, mo=end_mnth):
    """
    Takes a DataFrame
    Encodes "PropertyType" column
    Returns a defined training and test set for the DataFrame
    """
    yr_mo = []
    for i in self.df['CloseDate']:                                         # For each date in the "CloseDate" column
      yr, mo = i.year, i.month                                          # Define the year and month values of date i
      yr_mo.append([yr,mo])                                             # Append to "yr_mo" a list of date i's year and month
    te_set = [b for b in range(len(yr_mo)) if yr_mo[b] == [yr,mo]]   # Define a list of row #s with date 06/2026
    te_rng = te_set[0::len(te_set)-1]                                 # Define a list of the first and last row in "te_set"
    tr, te = self.df[0:te_rng[0]], self.df[te_rng[0]:te_rng[1]]             # Define the training and test sets of the inputted df
    return tr, te


  def XGB(self, tr, te, feat=crit_cols, targ=target, dep=6, l_rate=0.3, est=150):
    """
    Takes a training DataFrame and test DataFrame
    """
    x_tr = tr[feat].values            # Define the x_train set values
    y_tr = tr[targ].values            # Define the y_train set values
    x_te = te[feat].values            # Define the x_test set values
    y_te = te[targ].values            # Define the y_test set values

    model = XGBRegressor(random_state=0, max_depth=dep,
                         learning_rate=l_rate, n_estimators=est)        # Define Decision Tree Regression model
    model.fit(x_tr, y_tr)             # Fit training data to model
    y_pred = model.predict(x_te)      # Models the predicted y values from x_test values

    return y_te, y_pred


  def GBR(self, tr, te, feat=crit_cols, targ=target, dep=3, l_rate=0.1, est=100):
    """
    Takes a training DataFrame and test DataFrame
    """
    x_tr = tr[feat].values            # Define the x_train set values
    y_tr = tr[targ].values            # Define the y_train set values
    x_te = te[feat].values            # Define the x_test set values
    y_te = te[targ].values            # Define the y_test set values

    model = GradientBoostingRegressor(random_state=0, max_depth=dep,
                                      learning_rate=l_rate, n_estimators=est)        # Define Decision Tree Regression model
    model.fit(x_tr, y_tr)             # Fit training data to model
    y_pred = model.predict(x_te)      # Models the predicted y values from x_test values

    return y_te, y_pred


  def L_GBM(self, tr, te, feat=crit_cols, targ=target, dep=-1, l_rate=0.1, est=100):
    """
    Takes a training DataFrame and test DataFrame
    """
    x_tr, y_tr = tr[feat].values, tr[targ].values       # Define the x_train, y_train set values
    x_te, y_te = te[feat].values, te[targ].values       # Define the x_test, y_test set values

    lgb_tr = lgb.Dataset(x_tr, y_tr, free_raw_data=False)
    lgb_te = lgb.Dataset(x_te, y_te, free_raw_data=False)

    model = lgb.train(params={"max_depth": dep, "learning_rate": l_rate, "n_estimators": est},
                      train_set=lgb_tr, valid_sets=lgb_tr)          # Define Decision Tree Regression model
    y_pred = model.predict(x_te, num_iteration=model.best_iteration)      # Models the predicted y values from x_test values

    return y_te, y_pred


  def HGBR(self, tr, te, feat=crit_cols, targ=target, dep=None, l_rate=0.1):
    """
    Takes a training DataFrame and test DataFrame
    """
    x_tr = tr[feat].values            # Define the x_train set values
    y_tr = tr[targ].values            # Define the y_train set values
    x_te = te[feat].values            # Define the x_test set values
    y_te = te[targ].values            # Define the y_test set values

    model = HistGradientBoostingRegressor(random_state=0, max_depth=dep, learning_rate=l_rate)             # Define Decision Tree Regression model
    model.fit(x_tr, y_tr)             # Fit training data to model
    y_pred = model.predict(x_te)      # Models the predicted y values from x_test values

    return y_te, y_pred


  def log_transform(self, feat=log_cols, targ=target):
    log_df = self.df.copy()
    for col in feat+[targ]:
      new_col = []
      for val in log_df[col]:
        new_col.append(float(np.log(val)))
      log_df[col] = pd.DataFrame(new_col)
    return log_df


  def r2_eval(self, y_test, y_pred):
    r2 = r2_score(y_test, y_pred)       # Computes the r2 score of y_test and the predicted y
    return r2